[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning:huggingface_hub.*
    ignore:.*httpx.*
    ignore:.*StarletteDeprecationWarning.*


